# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1395, 737)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(310, 690, 181, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_delete = QtWidgets.QPushButton(Dialog)
        self.pushButton_delete.setGeometry(QtCore.QRect(500, 690, 181, 31))
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(30, 70, 1351, 601))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit.setGeometry(QtCore.QRect(960, 10, 291, 31))
        self.plainTextEdit.setPlainText("")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.pushButton_search = QtWidgets.QPushButton(Dialog)
        self.pushButton_search.setGeometry(QtCore.QRect(880, 690, 181, 31))
        self.pushButton_search.setObjectName("pushButton_search")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(840, 10, 111, 20))
        self.label.setObjectName("label")
        self.pushButton_delete_where = QtWidgets.QPushButton(Dialog)
        self.pushButton_delete_where.setGeometry(QtCore.QRect(690, 690, 181, 31))
        self.pushButton_delete_where.setObjectName("pushButton_delete_where")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "UPDATE TABLE"))
        self.pushButton_delete.setText(_translate("Dialog", "DELETE ALL"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "pretty_host"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "method"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "url"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "address"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "http_version"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "status_code"))
        self.pushButton_search.setText(_translate("Dialog", "Search"))
        self.label.setText(_translate("Dialog", "Client Or Server"))
        self.pushButton_delete_where.setText(_translate("Dialog", "DELETE Client Or Server"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
